server:
  port: 8080
spring:
  application:
    name: Auth_microservice
  datasource:
    url: jdbc:postgresql://auth-microservice-db:5432/auth_db
#    url: jdbc:postgresql://localhost:5432/auth_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
jwt:
  secret-key: weqjfnqbewfoi2371432yogr8qfwwgefb1ffh17803gf18g34fbasdsaf134fqf